services:
  postgres:
    image: postgres:15-alpine
    ports:
      - 5432:5432 # enables connecting locally via psql
    environment:
      POSTGRES_DB: timer_app_dev_db
      POSTGRES_HOST_AUTH_METHOD: trust
