export const supprtedColours = {
  white: "bg-white",
  slate: "bg-gray-400",
  gray: "bg-gray-400",
  stone: "bg-stone-400",
  red: "bg-red-400",
  orange: "bg-orange-400",
  amber: "bg-amber-400",
  yellow: "bg-yellow-400",
  lime: "bg-lime-400",
  green: "bg-green-400",
  emerald: "bg-emerald-400",
  teal: "bg-teal-400",
  cyan: "bg-cyan-400",
  sky: "bg-sky-400",
  blue: "bg-blue-400",
  indigo: "bg-indigo-400",
  violet: "bg-violet-400",
  purple: "bg-purple-400",
  fuchsia: "bg-fuchsia-400",
  pink: "bg-pink-400",
  magenta: "bg-magenta-400",
  rose: "bg-pink-400",
};

export const supprtedHoverColours = {
  white: "hover:bg-white",
  slate: "hover:bg-gray-500",
  gray: "hover:bg-gray-500",
  stone: "hover:bg-stone-500",
  red: "hover:bg-red-500",
  orange: "hover:bg-orange-500",
  amber: "hover:bg-amber-500",
  yellow: "hover:bg-yellow-500",
  lime: "hover:bg-lime-500",
  green: "hover:bg-green-500",
  emerald: "hover:bg-emerald-500",
  teal: "hover:bg-teal-500",
  cyan: "hover:bg-cyan-500",
  sky: "hover:bg-sky-500",
  blue: "hover:bg-blue-500",
  indigo: "hover:bg-indigo-500",
  violet: "hover:bg-violet-500",
  purple: "hover:bg-purple-500",
  fuchsia: "hover:bg-fuchsia-500",
  pink: "hover:bg-pink-500",
  magenta: "hover:bg-magenta-500",
  rose: "hover:bg-pink-500",
};

export const buttonHoverColours = {
  white: "hover:bg-white",
  slate: "hover:bg-gray-400",
  gray: "hover:bg-gray-400",
  stone: "hover:bg-stone-400",
  red: "hover:bg-red-400",
  orange: "hover:bg-orange-400",
  amber: "hover:bg-amber-400",
  yellow: "hover:bg-yellow-400",
  lime: "hover:bg-lime-400",
  green: "hover:bg-green-400",
  emerald: "hover:bg-emerald-400",
  teal: "hover:bg-teal-400",
  cyan: "hover:bg-cyan-400",
  sky: "hover:bg-sky-400",
  blue: "hover:bg-blue-400",
  indigo: "hover:bg-indigo-400",
  violet: "hover:bg-violet-400",
  purple: "hover:bg-purple-400",
  fuchsia: "hover:bg-fuchsia-400",
  pink: "hover:bg-pink-400",
  magenta: "hover:bg-magenta-400",
  rose: "hover:bg-pink-400",
};

export type Colour = keyof typeof supprtedColours;

export const randomColour = (): Colour => {
  const colours = Object.keys(supprtedColours) as Colour[];
  return colours[Math.floor(Math.random() * colours.length)];
};
